# lowcontrol_py.pyi

from typing import Any
import numpy as np
from typing import List

class RobotBmsData:
    battery_temp: int
    battery_alarm: int
    battery_soc: int
    battery_soh: int

class MotorCmd:
    pos: float
    vel: float
    tau: float
    kp: float
    kd: float
    motor_id: int

    def __init__(self) -> None: ...

class JoyData:
    def __init__(self) -> None: ...
    @property
    def axes(self) -> np.ndarray: ...
    @property
    def button(self) -> np.ndarray: ...

class NingImuData:
    def __init__(self) -> None: ...
    @property
    def ori(self) -> np.ndarray: ...
    @property
    def ori_cov(self) -> np.ndarray: ...
    @property
    def angular_vel(self) -> np.ndarray: ...
    @property
    def angular_vel_cov(self) -> np.ndarray: ...
    @property
    def linear_acc(self) -> np.ndarray: ...
    @property
    def linear_acc_cov(self) -> np.ndarray: ...

class MotorState:
    def __init__(self) -> None: ...
    pos: float
    vel: float
    tau: float
    motor_id: int
    error: int
    temperature: float

class LowController:
    @staticmethod
    def instance() -> "LowController": ...
    def init(self) -> bool: ...
    def set_joint(self, motorcmd: List[MotorCmd]) -> None: ...
    def get_joint_state(self) -> Any: ...
    def get_imu_data(self) -> NingImuData: ...
    def from_dds_get_joydata(self) -> JoyData: ...
    def getJointsIndex(self, jointname: str) -> int: ...
    def get_robot_bms_data(self) -> RobotBmsData: ...

class AoLionDriver:
    def __init__(self) -> None: ...
    def init(self, port: str, baudrate: int) -> bool: ...
    def getremotedata(self) -> JoyData: ...
