# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_control_pb2 as robot__control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlStub(object):
    """==========================================================================
    PND Robot Control Service
    对齐 FSM 架构：STOP / ZERO / STAND_WALK / MULTI_AGENT / MOTION_TRACK
    gRPC 默认端口: 50051, domain_id: 1
    ==========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMode = channel.unary_unary(
                '/pnd.robot.RobotControl/SetMode',
                request_serializer=robot__control__pb2.SetModeRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.SetVelocity = channel.unary_unary(
                '/pnd.robot.RobotControl/SetVelocity',
                request_serializer=robot__control__pb2.SetVelocityRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SetVelocityResponse.FromString,
                _registered_method=True)
        self.SetHeight = channel.unary_unary(
                '/pnd.robot.RobotControl/SetHeight',
                request_serializer=robot__control__pb2.SetHeightRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SetHeightResponse.FromString,
                _registered_method=True)
        self.SetMotion = channel.unary_unary(
                '/pnd.robot.RobotControl/SetMotion',
                request_serializer=robot__control__pb2.SetMotionRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SetMotionResponse.FromString,
                _registered_method=True)
        self.SetTrackingMotion = channel.unary_unary(
                '/pnd.robot.RobotControl/SetTrackingMotion',
                request_serializer=robot__control__pb2.SetTrackingMotionRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SetTrackingMotionResponse.FromString,
                _registered_method=True)
        self.GetRobotState = channel.unary_unary(
                '/pnd.robot.RobotControl/GetRobotState',
                request_serializer=robot__control__pb2.GetRobotStateRequest.SerializeToString,
                response_deserializer=robot__control__pb2.GetRobotStateResponse.FromString,
                _registered_method=True)
        self.SetControlMode = channel.unary_unary(
                '/pnd.robot.RobotControl/SetControlMode',
                request_serializer=robot__control__pb2.SetControlModeRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SetControlModeResponse.FromString,
                _registered_method=True)
        self.GetControlState = channel.unary_unary(
                '/pnd.robot.RobotControl/GetControlState',
                request_serializer=robot__control__pb2.GetControlStateRequest.SerializeToString,
                response_deserializer=robot__control__pb2.GetControlStateResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/pnd.robot.RobotControl/Shutdown',
                request_serializer=robot__control__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=robot__control__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class RobotControlServicer(object):
    """==========================================================================
    PND Robot Control Service
    对齐 FSM 架构：STOP / ZERO / STAND_WALK / MULTI_AGENT / MOTION_TRACK
    gRPC 默认端口: 50051, domain_id: 1
    ==========================================================================

    """

    def SetMode(self, request, context):
        """切换状态机模式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVelocity(self, request, context):
        """设置行走速度（预留，当前不接入）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHeight(self, request, context):
        """设置站立高度（预留，当前不接入）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMotion(self, request, context):
        """动作文件播放控制（MULTI_AGENT / MOTION_TRACK）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrackingMotion(self, request, context):
        """轨迹跟踪文件切换（MOTION_TRACK，支持运行中平滑切换）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """查询机器人状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControlMode(self, request, context):
        """切换控制范式 (Traditional / RL)，经 DDS ControlModeCmd_ 下发至 C++ 侧
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControlState(self, request, context):
        """读取 DDS rt/control_mode_state 反馈的控制范式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """关闭控制器（预留）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=robot__control__pb2.SetModeRequest.FromString,
                    response_serializer=robot__control__pb2.SetModeResponse.SerializeToString,
            ),
            'SetVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVelocity,
                    request_deserializer=robot__control__pb2.SetVelocityRequest.FromString,
                    response_serializer=robot__control__pb2.SetVelocityResponse.SerializeToString,
            ),
            'SetHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHeight,
                    request_deserializer=robot__control__pb2.SetHeightRequest.FromString,
                    response_serializer=robot__control__pb2.SetHeightResponse.SerializeToString,
            ),
            'SetMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMotion,
                    request_deserializer=robot__control__pb2.SetMotionRequest.FromString,
                    response_serializer=robot__control__pb2.SetMotionResponse.SerializeToString,
            ),
            'SetTrackingMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrackingMotion,
                    request_deserializer=robot__control__pb2.SetTrackingMotionRequest.FromString,
                    response_serializer=robot__control__pb2.SetTrackingMotionResponse.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=robot__control__pb2.GetRobotStateRequest.FromString,
                    response_serializer=robot__control__pb2.GetRobotStateResponse.SerializeToString,
            ),
            'SetControlMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControlMode,
                    request_deserializer=robot__control__pb2.SetControlModeRequest.FromString,
                    response_serializer=robot__control__pb2.SetControlModeResponse.SerializeToString,
            ),
            'GetControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControlState,
                    request_deserializer=robot__control__pb2.GetControlStateRequest.FromString,
                    response_serializer=robot__control__pb2.GetControlStateResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=robot__control__pb2.ShutdownRequest.FromString,
                    response_serializer=robot__control__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pnd.robot.RobotControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pnd.robot.RobotControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControl(object):
    """==========================================================================
    PND Robot Control Service
    对齐 FSM 架构：STOP / ZERO / STAND_WALK / MULTI_AGENT / MOTION_TRACK
    gRPC 默认端口: 50051, domain_id: 1
    ==========================================================================

    """

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/SetMode',
            robot__control__pb2.SetModeRequest.SerializeToString,
            robot__control__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/SetVelocity',
            robot__control__pb2.SetVelocityRequest.SerializeToString,
            robot__control__pb2.SetVelocityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/SetHeight',
            robot__control__pb2.SetHeightRequest.SerializeToString,
            robot__control__pb2.SetHeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/SetMotion',
            robot__control__pb2.SetMotionRequest.SerializeToString,
            robot__control__pb2.SetMotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrackingMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/SetTrackingMotion',
            robot__control__pb2.SetTrackingMotionRequest.SerializeToString,
            robot__control__pb2.SetTrackingMotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/GetRobotState',
            robot__control__pb2.GetRobotStateRequest.SerializeToString,
            robot__control__pb2.GetRobotStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControlMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/SetControlMode',
            robot__control__pb2.SetControlModeRequest.SerializeToString,
            robot__control__pb2.SetControlModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/GetControlState',
            robot__control__pb2.GetControlStateRequest.SerializeToString,
            robot__control__pb2.GetControlStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pnd.robot.RobotControl/Shutdown',
            robot__control__pb2.ShutdownRequest.SerializeToString,
            robot__control__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
