#!/usr/bin/env bash
# run-pr-image.sh — run a freshly built image on this machine for a quick test.
#
#   ./deploy/run-pr-image.sh <image-ref>   pull, generate compose, start
#   ./deploy/run-pr-image.sh --logs        follow the container's logs
#   ./deploy/run-pr-image.sh --shell       open a shell inside the container
#   ./deploy/run-pr-image.sh --status      show what is running, and from where
#   ./deploy/run-pr-image.sh --down        stop and remove it
#
# Intended for throwaway testing of an image built from a PR. It leaves the
# host's real deployment at /opt/phanthy-motus/docker-compose.yml untouched:
# the generated compose file lives on its own under PR_IMAGE_DIR, so `--down`
# cleans up completely.
#
# Every driver and the perception bundle ship a compose service fragment at
# /deploy/service.yml inside the image. This script extracts that fragment and
# wraps it in a standalone compose file — the same fragment Agent Core merges
# into the host compose file when you deploy from the web console. Using compose
# rather than a hand-written `docker run` is what keeps the privileged flags,
# host networking and device mounts each service needs exactly as its author
# declared them.
#
# For a lasting deployment, use the web console instead. This script is the
# quick "does it work" path.
#
# Requires: docker with the compose plugin. Nothing else — no python, no yq.
set -euo pipefail

PR_IMAGE_DIR="${PR_IMAGE_DIR:-/tmp/pr-image}"
COMPOSE_FILE="${PR_IMAGE_DIR}/docker-compose.yml"
STATE_FILE="${PR_IMAGE_DIR}/state"
SERVICE_YAML_PATH="/deploy/service.yml"

die()  { echo "Error: $*" >&2; exit 1; }
info() { echo "==> $*"; }

# The throwaway container used to read the service fragment out of the image.
# Cleaned up from an EXIT trap rather than a RETURN trap: the extraction exits
# the script when the fragment is missing, and `exit` inside a function does not
# fire RETURN traps — which leaked a `Created` container on that path.
TEMP_CID=""
cleanup_temp_container() {
    [ -n "$TEMP_CID" ] || return 0
    docker rm -f "$TEMP_CID" >/dev/null 2>&1 || true
    TEMP_CID=""
}
trap cleanup_temp_container EXIT

usage() {
    awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "$0"
}

require_docker() {
    command -v docker >/dev/null 2>&1 || die "docker is not installed."
    docker compose version >/dev/null 2>&1 \
        || die "the docker compose plugin is not available."
}

load_state() {
    [ -f "$STATE_FILE" ] || die "$(printf 'Nothing started yet.\nRun: %s <image-ref>' "$0")"
    # shellcheck disable=SC1090
    . "$STATE_FILE"
    [ -f "$COMPOSE_FILE" ] || die "Compose file missing: $COMPOSE_FILE"
}

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }

# ── Extract the service fragment out of the image ─────────────────────────────
#
# Via `docker create` + `docker cp` rather than `docker run --entrypoint cat`,
# so it works regardless of what the image contains — the same approach Agent
# Core uses (api/drivers.py:_deploy_sync).
extract_service_yaml() {
    local image="$1" dest="$2"
    TEMP_CID="$(docker create "$image" 2>/dev/null)" \
        || die "Could not create a container from $image"

    if ! docker cp "${TEMP_CID}:${SERVICE_YAML_PATH}" "$dest" >/dev/null 2>&1; then
        cat >&2 <<EOF
Error: this image has no ${SERVICE_YAML_PATH}, so it cannot be started here.

  Agent Core (the 'core' image) is the one target without a service fragment:
  it is the agent itself, and it is updated in place from the web console —
  the dashboard pulls the image and hands over to a restart helper. Starting a
  second copy by hand would fight the running one.

  Drivers and the perception bundle do ship one, and work with this script.
EOF
        exit 1
    fi
    cleanup_temp_container
}

# ── Build a standalone compose file from the fragment ─────────────────────────
#
# The fragment is a single mapping, `<service-name>: {...}`. Wrapping it needs
# only a `services:` header and two spaces of indent, so this is done with text
# transforms and carries no YAML-parser dependency.
generate_compose() {
    local fragment="$1" image="$2" out="$3"

    local service
    service="$(grep -m1 -E '^[A-Za-z0-9_.-]+:' "$fragment" | sed 's/:.*//')"
    [ -n "$service" ] || die "Could not find a service name in $SERVICE_YAML_PATH"

    {
        echo "# Generated by run-pr-image.sh — safe to delete."
        echo "# Source: ${SERVICE_YAML_PATH} inside ${image}"
        echo "services:"
        # Replace whatever the image declares (normally the __IMAGE__
        # placeholder) with the ref actually being tested, then indent.
        sed -E "s|^([[:space:]]*image:[[:space:]]*).*|\1${image}|" "$fragment" \
            | sed 's/^/  /'
    } > "$out"

    local container
    container="$(sed -nE 's|^[[:space:]]*container_name:[[:space:]]*(.*)$|\1|p' \
                 "$fragment" | head -1)"

    printf 'IMAGE=%s\nSERVICE=%s\nCONTAINER=%s\n' \
        "$image" "$service" "${container:-$service}" > "$STATE_FILE"

    echo "$service"
}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_up() {
    local image="$1"
    require_docker
    mkdir -p "$PR_IMAGE_DIR"

    info "Pulling $image"
    if ! docker pull "$image"; then
        # A pull failure is not fatal if the image is already here: the registry
        # may be briefly unreachable, or the image may have been built locally
        # and never pushed. Only give up when we have no copy at all.
        if docker image inspect "$image" >/dev/null 2>&1; then
            info "Pull failed, but the image is already present locally — using that."
        else
            die "$(printf 'Pull failed and the image is not present locally.\nCheck the reference, and that this host is logged in to the registry.')"
        fi
    fi

    local fragment="${PR_IMAGE_DIR}/service.yml"
    info "Reading ${SERVICE_YAML_PATH} from the image"
    extract_service_yaml "$image" "$fragment"

    local service
    service="$(generate_compose "$fragment" "$image" "$COMPOSE_FILE")"
    info "Generated $COMPOSE_FILE (service: $service)"

    # Replaces any previous run from this script, so repeated tests do not
    # collide on the container name declared in the fragment.
    info "Starting"
    compose up -d --remove-orphans

    load_state
    echo
    info "Running. Container: ${CONTAINER}"
    echo "  logs  : $0 --logs"
    echo "  shell : $0 --shell"
    echo "  stop  : $0 --down"
}

cmd_logs()   { load_state; compose logs -f; }
cmd_shell()  {
    load_state
    # bash is not guaranteed in every image; fall back to sh.
    compose exec "$SERVICE" bash 2>/dev/null || compose exec "$SERVICE" sh
}
cmd_down()   {
    load_state
    info "Stopping and removing ${CONTAINER}"
    compose down
    rm -f "$COMPOSE_FILE" "$STATE_FILE" "${PR_IMAGE_DIR}/service.yml"
    info "Removed. Nothing of this test remains."
}
cmd_status() {
    load_state
    echo "  image     : $IMAGE"
    echo "  service   : $SERVICE"
    echo "  container : $CONTAINER"
    echo "  compose   : $COMPOSE_FILE"
    echo
    compose ps
}

case "${1:-}" in
    --logs)          cmd_logs ;;
    --shell|--exec)  cmd_shell ;;
    --down|--stop)   cmd_down ;;
    --status|--ps)   cmd_status ;;
    -h|--help|help|"") usage ;;
    -*)              die "Unknown option: $1  (try --help)" ;;
    *)               cmd_up "$1" ;;
esac
