"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: pnd_adam.msg.dds_
  IDL file: BatteryData_.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import pnd_adam


@dataclass
@annotate.final
@annotate.autoid("sequential")
class BatteryData_(idl.IdlStruct, typename="pnd_adam.msg.dds_.BatteryData_"):
    timestamp_ms: types.int64
    voltage: types.float32
    current: types.float32
    power: types.float32
    wh_accumulated: types.float32
    status: str

