"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: pnd_adam.msg.dds_
  IDL file: LowCmd_.idl
"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import adam_u

@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowCmd_(idl.IdlStruct, typename="pnd_adam.msg.dds_.LowCmd_"):
    mode_pr: types.uint8
    motor_cmd: types.sequence['pndbotics_sdk_py.idl.pnd_adam.msg.dds_.MotorCmd_']
    reserve: types.uint32
