/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/rpdzkj/work/sdk/e1-sdk-dds-rk-new/idl/Robot_handTransfer.idl
  Source: /home/rpdzkj/work/sdk/e1-sdk-dds-rk-new/idl/Robot_handTransfer.hpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#ifndef DDSCXX__HOME_RPDZKJ_WORK_SDK_E1_SDK_DDS_RK_NEW_IDL_ROBOT_HANDTRANSFER_HPP_AF24FCBD695F65CD6248047C91420CDC
#define DDSCXX__HOME_RPDZKJ_WORK_SDK_E1_SDK_DDS_RK_NEW_IDL_ROBOT_HANDTRANSFER_HPP_AF24FCBD695F65CD6248047C91420CDC

#include <utility>
#include <ostream>
#include <cstdint>
#include <vector>

namespace PackageTransfer
{
class TransferRequest
{
private:
 std::vector<uint8_t> packet_data_;

public:
  TransferRequest() = default;

  explicit TransferRequest(
    const std::vector<uint8_t>& packet_data) :
    packet_data_(packet_data) { }

  const std::vector<uint8_t>& packet_data() const { return this->packet_data_; }
  std::vector<uint8_t>& packet_data() { return this->packet_data_; }
  void packet_data(const std::vector<uint8_t>& _val_) { this->packet_data_ = _val_; }
  void packet_data(std::vector<uint8_t>&& _val_) { this->packet_data_ = std::move(_val_); }

  bool operator==(const TransferRequest& _other) const
  {
    (void) _other;
    return packet_data_ == _other.packet_data_;
  }

  bool operator!=(const TransferRequest& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, TransferRequest const& rhs);

class TransferReply
{
private:
 std::vector<uint8_t> reply_data_;

public:
  TransferReply() = default;

  explicit TransferReply(
    const std::vector<uint8_t>& reply_data) :
    reply_data_(reply_data) { }

  const std::vector<uint8_t>& reply_data() const { return this->reply_data_; }
  std::vector<uint8_t>& reply_data() { return this->reply_data_; }
  void reply_data(const std::vector<uint8_t>& _val_) { this->reply_data_ = _val_; }
  void reply_data(std::vector<uint8_t>&& _val_) { this->reply_data_ = std::move(_val_); }

  bool operator==(const TransferReply& _other) const
  {
    (void) _other;
    return reply_data_ == _other.reply_data_;
  }

  bool operator!=(const TransferReply& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, TransferReply const& rhs);

} //namespace PackageTransfer

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::PackageTransfer::TransferRequest>::getTypeName()
{
  return "PackageTransfer::TransferRequest";
}

template <> constexpr bool TopicTraits<::PackageTransfer::TransferRequest>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::PackageTransfer::TransferRequest>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::PackageTransfer::TransferRequest>::type_map_blob_sz() { return 230; }
template<> constexpr unsigned int TopicTraits<::PackageTransfer::TransferRequest>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::PackageTransfer::TransferRequest>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x40,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xb7,  0x3f,  0xf1,  0x44,  0x73,  0xbd,  0x40, 
 0x88,  0x9b,  0x3e,  0x38,  0x6b,  0x91,  0x91,  0x00,  0x28,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02, 
 0xe4,  0xa9,  0x78,  0x4b,  0x76,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x9d,  0x67,  0x1d, 
 0x21,  0x04,  0xad,  0xe1,  0x2b,  0x69,  0x45,  0xde,  0x00,  0x4a,  0xbe,  0x00,  0x5e,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x29,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x21,  0x00,  0x00,  0x00, 
 0x50,  0x61,  0x63,  0x6b,  0x61,  0x67,  0x65,  0x54,  0x72,  0x61,  0x6e,  0x73,  0x66,  0x65,  0x72,  0x3a, 
 0x3a,  0x54,  0x72,  0x61,  0x6e,  0x73,  0x66,  0x65,  0x72,  0x52,  0x65,  0x71,  0x75,  0x65,  0x73,  0x74, 
 0x00,  0x00,  0x00,  0x00,  0x26,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x1e,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02,  0x0c,  0x00,  0x00,  0x00, 
 0x70,  0x61,  0x63,  0x6b,  0x65,  0x74,  0x5f,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x9d,  0x67,  0x1d,  0x21,  0x04,  0xad,  0xe1, 
 0x2b,  0x69,  0x45,  0xde,  0x00,  0x4a,  0xbe,  0xf1,  0xb7,  0x3f,  0xf1,  0x44,  0x73,  0xbd,  0x40,  0x88, 
 0x9b,  0x3e,  0x38,  0x6b,  0x91,  0x91, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::PackageTransfer::TransferRequest>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xb7,  0x3f,  0xf1,  0x44,  0x73,  0xbd,  0x40,  0x88,  0x9b,  0x3e,  0x38, 
 0x6b,  0x91,  0x91,  0x00,  0x2c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x9d,  0x67,  0x1d,  0x21,  0x04,  0xad,  0xe1,  0x2b,  0x69,  0x45,  0xde, 
 0x00,  0x4a,  0xbe,  0x00,  0x62,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

template <> constexpr const char* TopicTraits<::PackageTransfer::TransferReply>::getTypeName()
{
  return "PackageTransfer::TransferReply";
}

template <> constexpr bool TopicTraits<::PackageTransfer::TransferReply>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::PackageTransfer::TransferReply>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::PackageTransfer::TransferReply>::type_map_blob_sz() { return 226; }
template<> constexpr unsigned int TopicTraits<::PackageTransfer::TransferReply>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::PackageTransfer::TransferReply>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x40,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xf4,  0x3e,  0xb3,  0x44,  0x50,  0x0f,  0xe8, 
 0x1b,  0x0c,  0x0b,  0xa8,  0x63,  0x10,  0xc6,  0x00,  0x28,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02, 
 0x6c,  0x0b,  0x43,  0x85,  0x71,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x2a,  0x74,  0x6a, 
 0x83,  0xf1,  0xae,  0x2b,  0x57,  0xd3,  0x9e,  0xb0,  0xad,  0xc9,  0xd6,  0x00,  0x59,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x27,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00, 
 0x50,  0x61,  0x63,  0x6b,  0x61,  0x67,  0x65,  0x54,  0x72,  0x61,  0x6e,  0x73,  0x66,  0x65,  0x72,  0x3a, 
 0x3a,  0x54,  0x72,  0x61,  0x6e,  0x73,  0x66,  0x65,  0x72,  0x52,  0x65,  0x70,  0x6c,  0x79,  0x00,  0x00, 
 0x25,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02,  0x0b,  0x00,  0x00,  0x00,  0x72,  0x65,  0x70,  0x6c, 
 0x79,  0x5f,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x2a,  0x74,  0x6a,  0x83,  0xf1,  0xae,  0x2b,  0x57,  0xd3,  0x9e,  0xb0, 
 0xad,  0xc9,  0xd6,  0xf1,  0xf4,  0x3e,  0xb3,  0x44,  0x50,  0x0f,  0xe8,  0x1b,  0x0c,  0x0b,  0xa8,  0x63, 
 0x10,  0xc6, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::PackageTransfer::TransferReply>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xf4,  0x3e,  0xb3,  0x44,  0x50,  0x0f,  0xe8,  0x1b,  0x0c,  0x0b,  0xa8, 
 0x63,  0x10,  0xc6,  0x00,  0x2c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x2a,  0x74,  0x6a,  0x83,  0xf1,  0xae,  0x2b,  0x57,  0xd3,  0x9e,  0xb0, 
 0xad,  0xc9,  0xd6,  0x00,  0x5d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::PackageTransfer::TransferRequest>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::PackageTransfer::TransferRequest>::getTypeName();
    }
};

template <>
struct topic_type_name<::PackageTransfer::TransferReply>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::PackageTransfer::TransferReply>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::PackageTransfer::TransferRequest)
REGISTER_TOPIC_TYPE(::PackageTransfer::TransferReply)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::PackageTransfer::TransferRequest>();

namespace {
  static const volatile propvec &properties___PackageTransfer__TransferRequest = get_type_props<::PackageTransfer::TransferRequest>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::PackageTransfer::TransferRequest& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.packet_data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.packet_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::PackageTransfer::TransferRequest& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferRequest>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::PackageTransfer::TransferRequest& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.packet_data().size());
      if (!read(streamer, se_1))
        return false;
      instance.packet_data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.packet_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::PackageTransfer::TransferRequest& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferRequest>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::PackageTransfer::TransferRequest& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.packet_data().size());
      if (!move(streamer, se_1))
        return false;
      
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::PackageTransfer::TransferRequest& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferRequest>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::PackageTransfer::TransferRequest& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      // coverity[dead_error_line]
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::PackageTransfer::TransferRequest& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferRequest>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

template<>
const propvec &get_type_props<::PackageTransfer::TransferReply>();

namespace {
  static const volatile propvec &properties___PackageTransfer__TransferReply = get_type_props<::PackageTransfer::TransferReply>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::PackageTransfer::TransferReply& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.reply_data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.reply_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::PackageTransfer::TransferReply& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferReply>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::PackageTransfer::TransferReply& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.reply_data().size());
      if (!read(streamer, se_1))
        return false;
      instance.reply_data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.reply_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::PackageTransfer::TransferReply& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferReply>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::PackageTransfer::TransferReply& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.reply_data().size());
      if (!move(streamer, se_1))
        return false;
      
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::PackageTransfer::TransferReply& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferReply>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::PackageTransfer::TransferReply& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      // coverity[dead_error_line]
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::PackageTransfer::TransferReply& instance, key_mode key) {
  const auto &props = get_type_props<::PackageTransfer::TransferReply>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX__HOME_RPDZKJ_WORK_SDK_E1_SDK_DDS_RK_NEW_IDL_ROBOT_HANDTRANSFER_HPP_AF24FCBD695F65CD6248047C91420CDC
